MAIN_URL = 'https://stellarburgers.nomoreparties.site'
REG_URL = f'{MAIN_URL}/register'
LOGIN_URL = f'{MAIN_URL}/login'
PERSONAL_ACCOUNT_URL = f'{MAIN_URL}/account/profile'
FORGOT_PASSWORD_URL = f'{MAIN_URL}/forgot-password'
